### ISSUE TITLE
pls can you make also a windows relaese

### ISSUE THREAD

**Issue by gregor-hh** [XanderStrike/plexhooks#1]
love this project, I need it ... :) 👍 
hope there will be also windows releases.

and the ability to triger scripts and append payload values to the commandline as well.

want generate a telegram-bot push notification if someone trigger a media.play event, with informations in the pushmessage like „who played; „what/title“ and with picture thumb

brst regards

**Comment by XanderStrike** [comment]
This is a library for parsing plex webhooks, nothing more. You should include this library in whatever you write to accomplish those outcomes.
